server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/"your database name"
    username: "your username"
    password: "your password"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: devsync-group

jwt: 
  secret: c29tZXZlcnlzdHJvbmdzZWNyZXQtc3RyaW5nLWhlcmU=
  # change based on your requirements
  expiration: 3600000
