
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/"Your database name"
    username: your username
    password: your password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  access-secret: "secret key" - use strong one
  refresh-secret: "secret key" - use strong one
  access-expiration: 900000   # 15 minutes (in milliseconds)
  refresh-expiration: 604800000   # 7 days (in milliseconds)
