
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/artoken
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  access-secret: NzN4aG9xMkZKc3B2S1dwWmhtWUVNSXQwUnNXN3VtdTQ=
  refresh-secret: ZGh3M0s4VGJ6TExzQXNTN2p1VEdCTjQ5MEVma2hCY1k=
  access-expiration: 900000   # 15 minutes (in milliseconds)
  refresh-expiration: 604800000   # 7 days (in milliseconds)
